/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PollsIndexRouteImport } from './routes/polls/index'
import { Route as PollsCreateRouteImport } from './routes/polls/create'
import { Route as PollsIdRouteImport } from './routes/polls/$id'

const PollsIndexRoute = PollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsCreateRoute = PollsCreateRouteImport.update({
  id: '/polls/create',
  path: '/polls/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIdRoute = PollsIdRouteImport.update({
  id: '/polls/$id',
  path: '/polls/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/polls/$id': typeof PollsIdRoute
  '/polls/create': typeof PollsCreateRoute
  '/polls/': typeof PollsIndexRoute
}
export interface FileRoutesByTo {
  '/polls/$id': typeof PollsIdRoute
  '/polls/create': typeof PollsCreateRoute
  '/polls': typeof PollsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/polls/$id': typeof PollsIdRoute
  '/polls/create': typeof PollsCreateRoute
  '/polls/': typeof PollsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/polls/$id' | '/polls/create' | '/polls/'
  fileRoutesByTo: FileRoutesByTo
  to: '/polls/$id' | '/polls/create' | '/polls'
  id: '__root__' | '/polls/$id' | '/polls/create' | '/polls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PollsIdRoute: typeof PollsIdRoute
  PollsCreateRoute: typeof PollsCreateRoute
  PollsIndexRoute: typeof PollsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/polls/': {
      id: '/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof PollsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/create': {
      id: '/polls/create'
      path: '/polls/create'
      fullPath: '/polls/create'
      preLoaderRoute: typeof PollsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$id': {
      id: '/polls/$id'
      path: '/polls/$id'
      fullPath: '/polls/$id'
      preLoaderRoute: typeof PollsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PollsIdRoute: PollsIdRoute,
  PollsCreateRoute: PollsCreateRoute,
  PollsIndexRoute: PollsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
