/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PollsIdRouteImport } from './routes/polls/$id'
import { Route as AdminPollsIndexRouteImport } from './routes/admin/polls/index'
import { Route as AdminPollsCreateRouteImport } from './routes/admin/polls/create'
import { Route as AdminPollsIdRouteImport } from './routes/admin/polls/$id'

const PollsIdRoute = PollsIdRouteImport.update({
  id: '/polls/$id',
  path: '/polls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPollsIndexRoute = AdminPollsIndexRouteImport.update({
  id: '/admin/polls/',
  path: '/admin/polls/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPollsCreateRoute = AdminPollsCreateRouteImport.update({
  id: '/admin/polls/create',
  path: '/admin/polls/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPollsIdRoute = AdminPollsIdRouteImport.update({
  id: '/admin/polls/$id',
  path: '/admin/polls/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/polls/$id': typeof PollsIdRoute
  '/admin/polls/$id': typeof AdminPollsIdRoute
  '/admin/polls/create': typeof AdminPollsCreateRoute
  '/admin/polls/': typeof AdminPollsIndexRoute
}
export interface FileRoutesByTo {
  '/polls/$id': typeof PollsIdRoute
  '/admin/polls/$id': typeof AdminPollsIdRoute
  '/admin/polls/create': typeof AdminPollsCreateRoute
  '/admin/polls': typeof AdminPollsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/polls/$id': typeof PollsIdRoute
  '/admin/polls/$id': typeof AdminPollsIdRoute
  '/admin/polls/create': typeof AdminPollsCreateRoute
  '/admin/polls/': typeof AdminPollsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/polls/$id'
    | '/admin/polls/$id'
    | '/admin/polls/create'
    | '/admin/polls/'
  fileRoutesByTo: FileRoutesByTo
  to: '/polls/$id' | '/admin/polls/$id' | '/admin/polls/create' | '/admin/polls'
  id:
    | '__root__'
    | '/polls/$id'
    | '/admin/polls/$id'
    | '/admin/polls/create'
    | '/admin/polls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PollsIdRoute: typeof PollsIdRoute
  AdminPollsIdRoute: typeof AdminPollsIdRoute
  AdminPollsCreateRoute: typeof AdminPollsCreateRoute
  AdminPollsIndexRoute: typeof AdminPollsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/polls/$id': {
      id: '/polls/$id'
      path: '/polls/$id'
      fullPath: '/polls/$id'
      preLoaderRoute: typeof PollsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/polls/': {
      id: '/admin/polls/'
      path: '/admin/polls'
      fullPath: '/admin/polls/'
      preLoaderRoute: typeof AdminPollsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/polls/create': {
      id: '/admin/polls/create'
      path: '/admin/polls/create'
      fullPath: '/admin/polls/create'
      preLoaderRoute: typeof AdminPollsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/polls/$id': {
      id: '/admin/polls/$id'
      path: '/admin/polls/$id'
      fullPath: '/admin/polls/$id'
      preLoaderRoute: typeof AdminPollsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PollsIdRoute: PollsIdRoute,
  AdminPollsIdRoute: AdminPollsIdRoute,
  AdminPollsCreateRoute: AdminPollsCreateRoute,
  AdminPollsIndexRoute: AdminPollsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
